name: Deploy to GitHub Pages

# Quando o workflow será acionado: sempre que houver push na branch 'main'
on:
  push:
    branches:
      - feature-atualizacoes-estacoes 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Autenticar na API e salvar a resposta em um arquivo JSON estático
      - name: Authenticate and fetch API data
        run: |
          echo "API_IDENTIFIER=${{ secrets.API_IDENTIFIER }}" >> $GITHUB_ENV
          echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> $GITHUB_ENV
          node scripts/fetchData.js  # Esse arquivo vai fazer a autenticação e salvar os dados

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
